package com.aesthetic.backend.dto.response

enum class ErrorCode {
    VALIDATION_ERROR,
    INVALID_CREDENTIALS,
    FORBIDDEN,
    PLAN_LIMIT_EXCEEDED,
    CLIENT_BLACKLISTED,
    RESOURCE_NOT_FOUND,
    TENANT_NOT_FOUND,
    APPOINTMENT_CONFLICT,
    APPOINTMENT_INVALID_STATUS,
    APPOINTMENT_PAST_DATE,
    NO_AVAILABLE_STAFF,
    DUPLICATE_RESOURCE,
    ACCOUNT_LOCKED,
    NOTIFICATION_DELIVERY_FAILED,
    RATE_LIMIT_EXCEEDED,
    INTERNAL_ERROR
}
