CREATE TABLE appointments (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    tenant_id VARCHAR(36) NOT NULL,
    client_id VARCHAR(36),
    client_name VARCHAR(255) NOT NULL,
    client_email VARCHAR(255) NOT NULL DEFAULT '',
    client_phone VARCHAR(50) NOT NULL DEFAULT '',
    primary_service_id VARCHAR(36),
    staff_id VARCHAR(36),
    date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    total_duration_minutes INT NOT NULL DEFAULT 0,
    total_price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    notes TEXT,
    status ENUM('PENDING','CONFIRMED','IN_PROGRESS','COMPLETED','CANCELLED','NO_SHOW') NOT NULL DEFAULT 'PENDING',
    cancelled_at TIMESTAMP(6) NULL,
    cancellation_reason VARCHAR(500),
    recurring_group_id VARCHAR(36),
    recurrence_rule VARCHAR(20),
    reminder_24h_sent BOOLEAN NOT NULL DEFAULT FALSE,
    reminder_1h_sent BOOLEAN NOT NULL DEFAULT FALSE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_appt_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_appt_client FOREIGN KEY (client_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_appt_primary_service FOREIGN KEY (primary_service_id) REFERENCES services(id) ON DELETE SET NULL,
    CONSTRAINT fk_appt_staff FOREIGN KEY (staff_id) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_appt_conflict (tenant_id, staff_id, date, start_time, end_time, status),
    INDEX idx_appt_tenant_date (tenant_id, date),
    INDEX idx_appt_status (tenant_id, status),
    INDEX idx_appt_client (tenant_id, client_id),
    INDEX idx_appt_recurring (recurring_group_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_turkish_ci;
